---
name: build-and-push-image
on:
  workflow_dispatch:
  push:
    branches:
      - $BRANCH_NAME
env:
  IMAGE_TAG: ${{ github.sha }}
  AWS_RESION: $AWS_REGION
  ECR_REPOSITORY: $ECR_REPOSITORY
  ENV_S3_BUCKET: $ENV_S3_BUCKET
  DOCKERFILE_NAME: $DOCKERFILE_NAME
  BUILD_PATH: $BUILD_PATH
  ENV_FILE_NAME: $ENV_FILE_NAME
jobs:
  deploy:
    name: Build image
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and Push Server Image
        working-directory: ${{ env.BUILD_PATH }}
        run: |
$PRE_BUILD_SCRIPT
          aws s3 cp s3://${{ env.ENV_S3_BUCKET }}/${{env.ENV_FILE_NAME}} .env
          docker build --platform linux/x86_64 -f ${{ env.DOCKERFILE_NAME }} -t ${{ env.ECR_REPOSITORY }} .
          docker tag ${{ env.ECR_REPOSITORY }} ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}
          docker push ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}
